services:
  app1:
    build: ./app1
    image: node-app1
    hostname: app1
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - DB_HOST=app1_db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=app1db
    networks:
      - app1_net
      - public_net
  
  app1_db:
    hostname: app1_db
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app1db
    volumes:
      - app1_db_data:/var/lib/mysql
    networks:
      app1_net:
        aliases:
          - app1_db

  app2:
    image: traefik/whoami
    hostname: app2
    ports:
      - "127.0.0.1:3001:80"
    networks:
      - app2_net
      - public_net

  rproxy_nginx:
    image: nginx:latest
    hostname: rproxy_nginx
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - public_net

volumes:
  app1_db_data:
    name: app1_db_data

networks:
  app1_net:
    name: app1_net
    driver: bridge

  app2_net:
    name: app2_net
    driver: bridge

  public_net:
    external: true
    name: public_net