services:
  docker-registry:
    image: registry:latest
    restart: always
    container_name: docker-registry
    hostname: docker-registry
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry

volumes:
  registry_data:
    driver: local